### ISSUE TITLE
Unable to create resource using BBCode->Markdown converter system

### ISSUE THREAD

**Issue by lokka30** [HangarMC/Hangar#1015]
### Observed/problematic behavior

Unable to create resource. Important context: using the BBCode-Markdown converter and clicked Save as Home Page.

Once that error notification disappeared, the page just got stuck on 'Creating...'

![image](https://user-images.githubusercontent.com/59464084/201059330-d513c0e7-d778-4ad6-92ce-cab4c616e3c4.png)

### Expected behavior

Resource would be created without the errors 

### Steps to reproduce

- Create a resource
  - Use the Markdown -> BBCode converter
  - In that converter page, click 'save as home page'
  - Hit create :)

**Comment by lokka30** [comment]
Update: Encountered same issue without using the BBCode converter at all.

**Comment by MiniDigger** [comment]
```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method regex(java.lang.String,io.papermc.hangar.util.PatternWrapper) cannot be found on type io.papermc.hangar.controller.validations.Validations
	at org.springframework.expression.spel.ast.MethodReference.findAccessorForMethod(MethodReference.java:225) ~[spring-expression-5.3.23.jar!/:5.3.23]
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:135) ~[spring-expression-5.3.23.jar!/:5.3.23]
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:55) ~[spring-expression-5.3.23.jar!/:5.3.23]
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:386) ~[spring-expression-5.3.23.jar!/:5.3.23]
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:92) ~[spring-expression-5.3.23.jar!/:5.3.23]
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117) ~[spring-expression-5.3.23.jar!/:5.3.23]
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:376) ~[spring-expression-5.3.23.jar!/:5.3.23]
	at io.papermc.hangar.controller.validations.Validate$ValidateConstraintValidator.isValid(Validate.java:46) ~[classes!/:0.0.1-SNAPSHOT]

```
