### ISSUE TITLE
Navigation completely breaks if you switch pages while another is loading

### ISSUE THREAD

**Issue by NoahvdAa** [HangarMC/Hangar#1073]
### Observed/problematic behavior

When you navigate between pages too fast navigation breaks completely. The url still changes in the browser navigation bar (and the 'selected page' thing also updates in the site navbar), but the page stays the same, see video below:

https://user-images.githubusercontent.com/44026893/210782359-26f58a18-e8ab-4576-8114-1e9ba07e8581.mov

### Expected behavior

Navigation should work

### Steps to reproduce

Click on a page, then while that page is loading click to another.

### Other

The account settings navigation at the end did work, I just cut off the response since it might contain sensitive information.

**Comment by MiniDigger** [comment]
I enabled source maps now, if you can repro, please open the JS console and copy the stack trace you see there.

**Comment by NoahvdAa** [comment]
The trace still looks fairly minified, but this is what I got:
```
TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (runtime-dom.esm-bundler.js:35:30)
    at yl.W [as fn] (runtime-core.esm-bundler.js:5713:17)
    at yl.run (reactivity.esm-bundler.js:187:25)
    at y.update (runtime-core.esm-bundler.js:5745:56)
    at oe (runtime-core.esm-bundler.js:5570:26)
    at J (runtime-core.esm-bundler.js:5503:13)
    at v (runtime-core.esm-bundler.js:5101:21)
    at e0 (runtime-core.esm-bundler.js:1297:13)
    at Object.process (runtime-core.esm-bundler.js:1188:13)
    at v (runtime-core.esm-bundler.js:5107:26)
Wy @ runtime-core.esm-bundler.js:228
lo @ runtime-core.esm-bundler.js:206
zr @ runtime-core.esm-bundler.js:160
wh @ runtime-core.esm-bundler.js:390
Promise.then (async)
bh @ runtime-core.esm-bundler.js:282
Gs @ runtime-core.esm-bundler.js:276
(anonymous) @ runtime-core.esm-bundler.js:5743
Ic @ reactivity.esm-bundler.js:397
ua @ reactivity.esm-bundler.js:387
Sl @ reactivity.esm-bundler.js:1011
(anonymous) @ reactivity.esm-bundler.js:1137
Ic @ reactivity.esm-bundler.js:397
ua @ reactivity.esm-bundler.js:382
Sl @ reactivity.esm-bundler.js:1011
(anonymous) @ reactivity.esm-bundler.js:1137
Ic @ reactivity.esm-bundler.js:397
ua @ reactivity.esm-bundler.js:382
Sl @ reactivity.esm-bundler.js:1011
set value @ reactivity.esm-bundler.js:1048
B @ vue-router.mjs:3334
(anonymous) @ vue-router.mjs:3207
Promise.then (async)
R @ vue-router.mjs:3174
C @ vue-router.mjs:3099
a @ vue-router.mjs:2189
zr @ runtime-core.esm-bundler.js:157
nr @ runtime-core.esm-bundler.js:166
r @ runtime-dom.esm-bundler.js:345
```
